/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AbstractsRouteImport } from './routes/abstracts'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProgrammeRouteImport } from './routes/programme'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ResearchAreasRouteImport } from './routes/research-areas'
import { Route as SpeakersRouteImport } from './routes/speakers'
import { Route as VenueRouteImport } from './routes/venue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AbstractsRoute = AbstractsRouteImport.update({
  id: '/abstracts',
  path: '/abstracts',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeRoute = ProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAreasRoute = ResearchAreasRouteImport.update({
  id: '/research-areas',
  path: '/research-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersRoute = SpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueRoute = VenueRouteImport.update({
  id: '/venue',
  path: '/venue',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abstracts': typeof AbstractsRoute
  '/awards': typeof AwardsRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/programme': typeof ProgrammeRoute
  '/registration': typeof RegistrationRoute
  '/research-areas': typeof ResearchAreasRoute
  '/speakers': typeof SpeakersRoute
  '/venue': typeof VenueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abstracts': typeof AbstractsRoute
  '/awards': typeof AwardsRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/programme': typeof ProgrammeRoute
  '/registration': typeof RegistrationRoute
  '/research-areas': typeof ResearchAreasRoute
  '/speakers': typeof SpeakersRoute
  '/venue': typeof VenueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/abstracts': typeof AbstractsRoute
  '/awards': typeof AwardsRoute
  '/committee': typeof CommitteeRoute
  '/contact': typeof ContactRoute
  '/programme': typeof ProgrammeRoute
  '/registration': typeof RegistrationRoute
  '/research-areas': typeof ResearchAreasRoute
  '/speakers': typeof SpeakersRoute
  '/venue': typeof VenueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/abstracts'
    | '/awards'
    | '/committee'
    | '/contact'
    | '/programme'
    | '/registration'
    | '/research-areas'
    | '/speakers'
    | '/venue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/abstracts'
    | '/awards'
    | '/committee'
    | '/contact'
    | '/programme'
    | '/registration'
    | '/research-areas'
    | '/speakers'
    | '/venue'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/abstracts'
    | '/awards'
    | '/committee'
    | '/contact'
    | '/programme'
    | '/registration'
    | '/research-areas'
    | '/speakers'
    | '/venue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AbstractsRoute: typeof AbstractsRoute
  AwardsRoute: typeof AwardsRoute
  CommitteeRoute: typeof CommitteeRoute
  ContactRoute: typeof ContactRoute
  ProgrammeRoute: typeof ProgrammeRoute
  RegistrationRoute: typeof RegistrationRoute
  ResearchAreasRoute: typeof ResearchAreasRoute
  SpeakersRoute: typeof SpeakersRoute
  VenueRoute: typeof VenueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abstracts': {
      id: '/abstracts'
      path: '/abstracts'
      fullPath: '/abstracts'
      preLoaderRoute: typeof AbstractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programme': {
      id: '/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof ProgrammeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-areas': {
      id: '/research-areas'
      path: '/research-areas'
      fullPath: '/research-areas'
      preLoaderRoute: typeof ResearchAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers': {
      id: '/speakers'
      path: '/speakers'
      fullPath: '/speakers'
      preLoaderRoute: typeof SpeakersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue': {
      id: '/venue'
      path: '/venue'
      fullPath: '/venue'
      preLoaderRoute: typeof VenueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AbstractsRoute: AbstractsRoute,
  AwardsRoute: AwardsRoute,
  CommitteeRoute: CommitteeRoute,
  ContactRoute: ContactRoute,
  ProgrammeRoute: ProgrammeRoute,
  RegistrationRoute: RegistrationRoute,
  ResearchAreasRoute: ResearchAreasRoute,
  SpeakersRoute: SpeakersRoute,
  VenueRoute: VenueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
